---
services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - /var/nginx/conf.d:/etc/nginx/conf.d
      - /var/nginx/certs:/etc/nginx/nginx-certs
      - /var/nginx/data-site:/usr/share/nginx/html
      - /var/nginx/log:/var/log/nginx/log
    networks:
      - it4innov-lab
networks:
  it4innov-lab:
    driver: bridge
